site_name: Кошкокрафт
site_author: Всекотец
site_url: https://wiki.catcraftmc.ru/

# repo_url: https://github.com/szarkans/szarkans.github.io
# repo_name: Вики КК
edit_uri: https://github.com/szarkans/szarkans.github.io/edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: indigo
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil   
  language: ru
  features:
    - content.tabs.link
 #   - navigation.instant
  #  - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tooltips
    - toc.follow
 #   - toc.integrate
    - content.action.edit
  logo: assets/icon_purple.png
  favicon: assets/icon.png
  font:
    text: Inter
    code: Fira Code
markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - tables
  - pymdownx.critic
  - pymdownx.snippets:
      auto_append:
        - includes/links.md
  - toc:
      permalink: "#"
      separator: "_"
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - def_list
  - md_in_html
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - stylesheets/extra.css
  - stylesheets/my.css
  - stylesheets/admonitions.css
  - stylesheets/before_after.css
  - stylesheets/snake.css
plugins:
  - search
  - blog:
      blog_dir: updates
      blog_toc: true
      post_excerpt_max_authors: 2
  - open-in-new-tab
  - minify:
      minify_html: true
  - exclude:
      glob:
        - includes/*
        - docs/deprecated/*
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
 # - javascripts/players.js
  - javascripts/effects.js
  - javascripts/anchors.js
  - javascripts/img_expand.js
  - javascripts/before_after.js
  - javascripts/oneko.js
  - javascripts/oneko-element.js
  #- javascripts/snake.js
  - javascripts/carousel.js
watch:
  - includes
extra: 
  consent:
    title: Одобри печеньки!
    description:
      Мы используем твои куки для просмотра аналитики нашей Вики (кто, что, где, какую страницу смотрят чаще и т.п.)
  status:
    new: Недавно обновлено!
    inprogress: Статья не завершена
    beta: Эта фича в Бете!
  analytics: 
    provider: google
    property: G-X3KCR2ZW65
  social:
    - icon: simple/discord
      link: https://discord.gg/6f3FwFRJWC
      name: Наш Дискорд
    - icon: simple/vk
      link: https://vk.com/catcraftmc
      name: Наш ВК
    - icon: material/map
      link: https://map.catcraftmc.ru
      name: Наша Карта
nav:
  - '': index.md
  - О сервере:
    - info/faq.md
    - info/map.md
    - info/mods.md
    - info/farm.md
    - 'Информация':
      - info/admins.md
      - info/donate.md
      - info/guide.md
      - info/for_media.md
      - info/brandbook.md
      - info/banlist.md
      - info/prefixes.md
    - 'Правила и законы':
      - info/rules/rules.md
      - info/rules/laws.md
    - "Бюрократия":
      - info/oferta.md
  - Геймплей:
    - gameplay/unique/qol.md
    - gameplay/unique/commands.md
    - gameplay/unique/land_protection.md
    - gameplay/unique/decor.md
    - gameplay/unique/artmap.md
    - gameplay/unique/brewery.md
    - gameplay/unique/fishing.md
    - gameplay/unique/npc.md
    - gameplay/unique/clans.md
    - gameplay/unique/cpm.md
    - gameplay/unique/voicechat.md
    - gameplay/unique/resourcepack.md
    - gameplay/unique/datapacks.md
    - Роллплей:
      - gameplay/roleplay/goverment.md
      - gameplay/roleplay/police.md
    - Награды игрокам:
      - gameplay/rewards/list.md
      - gameplay/rewards/catpass.md
  - Бестиарий:
    - "items/main.md"
    # - Мобы:
    #    - "mobs/red.md"
    #    - "mobs/haunted_weapon.md" 
    - Ванилла:
      - "items/vanilla/vanilla_crafts.md"
      - "items/vanilla/vanilla_edits.md"
    - Кошкокрафт:
      - Блоки:
        - "items/blocks/gycha.md"
        - "items/blocks/compressed.md"
        - "items/blocks/light.md"
        - "items/blocks/invis_frame.md"
        - "items/blocks/decor_table.md"
        - "items/blocks/cabinets.md"
        - "items/blocks/chess.md"
      - Используемое:
        - "items/usable/kplus.md"
        - "items/usable/cattrack.md"
        - "items/usable/scroll.md"
      - Инструменты:
        - "items/custom_items/gh.md"
        - "items/custom_items/echo_bell.md"
        - "items/custom_items/paint_brush.md"
      - Прочее:
        - "items/custom_items/plushie.md"
        - "items/custom_items/kotomat.md"
        - "items/custom_items/cotopedia.md"
        - "items/custom_items/holy_books.md"
        - "items/custom_items/dummy.md"
        - "items/custom_items/cards.md"
        - "items/custom_items/dice.md"
    
  - Гайды:
    - Игровое:
      - guides/gameplay/create_shop.md
      - guides/gameplay/set_skin.md
      - guides/gameplay/rgb_nick.md
      - guides/gameplay/create_event.md
    - Техническое:
      - guides/tech/mod_download.md
      - guides/tech/mod_errors.md
      - guides/tech/skins_tlauncher.md
    - Разное:
      - guides/other/launcher.md
      - guides/other/edit_wiki.md
  - История сервера:
    - server-history/1season.md
    - server-history/2season.md
    - server-history/3season.md
    - server-history/4season.md
    - server-history/5season.md
    - server-history/6season.md
  - Обновления:
    - updates/index.md
  # - 6 сезон:
  #   - 6season/notworking.md
  #   - 6season/rules.md
  #   #- 6season/donates.md
  #   - 6season/advancements.md
  #   - 6season/new_items.md
  #   # - 6season/fishing.md
  #   - 6season/villager_rebalance.md
  #   - 6season/commands.md
  #   - 6season/qol.md
  #   - 6season/map.md
  #   # - 6season/datapacks.md
  #   - 6season/wiki.md
  #   - 6season/brewery.md
  #   - 6season/npc.md
